version: "3"
services:
  www:
    build: .
    ports:
      - "80:80"
    networks:
      - default
    environment:
      - DB_HOST=db 
      - DB_USER=root
      - DB_PASS=root
      - EMAIL_HOST=
      - EMAIL_USER=
      - EMAIL_PASS=
      - MAPS_KEY=
      - SMS_USER=
      - SMS_KEY=
      - VIDEOSDK_KEY=
      - VIDEOSDK_SECRERT=
      - STRIPE_SECRET=
      - STRIPE_PUBLISHABLE=
    volumes:
      - ".:/var/www"       
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./scripts/database.sql:/docker-entrypoint-initdb.d/1.sql"