version: "3"
services:
  www:
    build: .
    ports:
      - "80:80"
    networks:
      - default
    environment:
      - DB_HOST=db 
    volumes:
      - ".:/var/www"       
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./scripts/database.sql:/docker-entrypoint-initdb.d/1.sql"